services:
  worker:
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
      target: development
    command: yarn start:dev main
    env_file:
      - ./apps/worker/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password@01
